const fabricsList = [
    {
        name: 'Sheet Music',
        image: '/fabrics/new/IMG-1441.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1441.jpg',        
        colors: ['brown'],
        limited: false,
    },
    {
        name: 'Espresso',
        image: '/fabrics/new/IMG-1442.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1442.jpg',        
        colors: ['brown', 'black', 'white'],
        limited: false,
    },
    {
        name: 'Breakfast',
        image: '/fabrics/new/IMG-1443.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1443.jpg',        
        colors: ['blue', 'pink', 'red', 'orange', 'yellow', 'white', 'brown'],
        limited: false,
    },
    {
        name: 'Coffee Beans',
        image: '/fabrics/new/IMG-1444.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1444.jpg',        
        colors: ['brown'],
        limited: false,
    },
    {
        name: 'Pumpkin Drinks',
        image: '/fabrics/new/IMG-1445.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1445.jpg',        
        colors: ['orange', 'brown', 'white'],
        limited: false,
    },
    {
        name: 'Cookie',
        image: '/fabrics/new/IMG-1446.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1446.jpg',        
        colors: ['brown', 'black'],
        limited: false,
    },
    {
        name: 'Fall Leaves',
        image: '/fabrics/new/IMG-1447.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1447.jpg',        
        colors: ['red', 'pink', 'orange', 'yellow', 'green', 'blue', 'purple'],
        limited: false,
    },
    {
        name: 'Avacados',
        image: '/fabrics/new/IMG-1448.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1448.jpg',        
        colors: ['green', 'yellow', 'brown', 'white', 'black'],
        limited: false,
    },
    {
        name: 'Digital Camo',
        image: '/fabrics/new/IMG-1449.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1449.jpg',        
        colors: ['green', 'brown', 'black', 'white'],
        limited: false,
    },
    {
        name: 'Lepoard',
        image: '/fabrics/new/IMG-1450.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1450.jpg',        
        colors: ['browm', 'black', 'white'],
        limited: false,
    },
    {
        name: 'Maryland Flag',
        image: '/fabrics/new/IMG-1451.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1451.jpg',        
        colors: ['orange', 'red', 'black', 'white'],
        limited: false,
    },
    {
        name: 'Sport Balls',
        image: '/fabrics/new/IMG-1452.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1452.jpg',        
        colors: ['grey', 'white', 'orange', 'yellow', 'black', 'red'],
        limited: false,
    },
    {
        name: 'Pacman',
        image: '/fabrics/new/IMG-1453.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1453.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Snowmen',
        image: '/fabrics/new/IMG-1454.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1454.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Snowflakes',
        image: '/fabrics/new/IMG-1455.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1455.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Geometric Christmas',
        image: '/fabrics/new/IMG-1456.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1456.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Pretty',
        image: '/fabrics/new/IMG-1457.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1457.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Teal Stripes',
        image: '/fabrics/new/IMG-1458.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1458.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Blue Stripes',
        image: '/fabrics/new/IMG-1459.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1459.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Another Blue Stripes',
        image: '/fabrics/new/IMG-1460.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1460.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Yellow Stripes',
        image: '/fabrics/new/IMG-1461.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1461.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Red Polka Dots',
        image: '/fabrics/new/IMG-1462.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1462.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Yuck',
        image: '/fabrics/new/IMG-1464.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1464.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Holly & Rose',
        image: '/fabrics/new/IMG-1465.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1465.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Bam Boo',
        image: '/fabrics/new/IMG-1466.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1466.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'Snow',
        image: '/fabrics/new/IMG-1467.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1467.jpg',        
        colors: ['black'],
        limited: false,
    },
    {
        name: 'My Couch',
        image: '/fabrics/new/IMG-1468.jpg',
        thumbnail: '/fabrics/new/thumbnails/IMG-1468.jpg',        
        colors: ['black'],
        limited: false,
    },




    {
        name: 'Black',
        image: '/fabrics/DSC_0573_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0573_Original.jpg',        
        colors: ['black'],
        limited: true,
    },
    {
        name: 'Faux Denim',
        image: '/fabrics/DSC_0562_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0562_Original.jpg',
        colors: ['blue', 'grey', 'black'],
        limited: false,
    },
    {
        name: 'Grey',
        image: '/fabrics/DSC_0576_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0576_Original.jpg',
        colors: ['grey'],
        limited: false,
    },
    {
        name: 'White',
        image: '/fabrics/DSC_0570_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0570_Original.jpg',
        colors: ['white'],
        limited: false,
    },
    {
        name: 'Pale Blue',
        image: '/fabrics/DSC-0954-Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC-0954-Original.jpg',
        colors: ['blue'],
        limited: false,
    },
    {
        name: 'Sky Blue',
        image: '/fabrics/DSC-0955-Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC-0955-Original.jpg',
        colors: ['blue'],
        limited: false,
    },
    {
        name: 'Seafoam',
        image: '/fabrics/DSC-0956-Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC-0956-Original.jpg',
        colors: ['blue', 'green'],
        limited: false,
    },
    {
        name: 'Teal',
        image: '/fabrics/DSC_0564_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0564_Original.jpg',
        colors: ['blue', 'green'],
        limited: false,
    },
    {
        name: 'Light Green',
        image: '/fabrics/DSC_0569_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0569_Original.jpg',
        colors: ['green'],
        limited: false,
    },
    {
        name: 'Green',
        image: '/fabrics/DSC_0568_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0568_Original.jpg',
        colors: ['green'],
        limited: false,
    },
    {
        name: 'Blue',
        image: '/fabrics/DSC_0565_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0565_Original.jpg',
        colors: ['blue'],
        limited: false,
    },
    {
        name: 'Purple',
        image: '/fabrics/DSC_0574_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0574_Original.jpg',
        colors: ['purple'],
        limited: false,
    },
    {
        name: 'Pink',
        image: '/fabrics/DSC_0577_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0577_Original.jpg',
        colors: ['pink'],
        limited: false,
    },
    {
        name: 'Light Pink',
        image: '/fabrics/DSC_0575_Original.jpg',
        thumbnail: '/fabrics/thumbnails/DSC_0575_Original.jpg',
        colors: ['pink'],
        limited: false,
    },
    {
        name: 'Black Mini Polka Dots',
        image: '/fabrics/IMG_0396.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0396.jpg',
        colors: ['black', 'white'],
        limited: true,
    },
    {
        name: 'Grey Polka Dots',
        image: '/fabrics/IMG_0392.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0392.jpg',
        colors: ['grey', 'white'],
        limited: false,
    },
    {
        name: 'Brown Polka Dots',
        image: '/fabrics/IMG_0394.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0394.jpg',
        colors: ['brown', 'white'],
        limited: true,
    },
    {
        name: 'Green Polka Dots',
        image: '/fabrics/IMG_0393.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0393.jpg',
        colors: ['green', 'white'],
        limited: false,
    },
    {
        name: 'Pink Mini Polka Dots',
        image: '/fabrics/IMG_0395.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0395.jpg',
        colors: ['pink', 'white'],
        limited: false,
    },
    {
        name: 'Pink Fleur-de-lis',
        image: '/fabrics/IMG_0399.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0399.jpg',
        colors: ['pink', 'white'],
        limited: true,
    },
    {
        name: 'Small Gold Flowers',
        image: '/fabrics/IMG_0387.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0387.jpg',
        colors: ['yellow', 'white'],
        limited: false,
    },
    {
        name: 'Small Gold Ornamental',
        image: '/fabrics/IMG_0389.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0389.jpg',
        colors: ['yellow', 'white'],
        limited: false,
    },
    {
        name: 'Yellow Gingham',
        image: '/fabrics/IMG-0749.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0749.jpg',
        colors: ['yellow', 'white'],
        limited: false,
    },
    {
        name: 'Pink Gingham',
        image: '/fabrics/IMG_0398.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0398.jpg',
        colors: ['pink', 'white'],
        limited: true,
    },
    {
        name: 'Blue Stripes',
        image: '/fabrics/IMG-0743.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0743.jpg',
        colors: ['blue', 'black', 'white'],
        limited: true,
    },
    {
        name: 'Thin Multicolor Stripes',
        image: '/fabrics/IMG_0397.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0397.jpg',
        colors: ['red', 'yellow', 'green', 'blue', 'purple', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Thick Multicolor Strips',
        image: '/fabrics/IMG_0418.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0418.jpg',
        colors: ['red', 'yellow', 'green', 'purple', 'white', 'rainbow'],
        limited: true,
    },
    {
        name: 'Purple & Pink Zigzags',
        image: '/fabrics/IMG_0428.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0428.jpg',
        colors: ['purple', 'pink'],
        limited: false,
    },
    {
        name: 'Orange & Navy Squiggles',
        image: '/fabrics/IMG_0443.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0443.jpg',
        colors: ['orange', 'blue', 'white'],
        limited: false,
    },
    {
        name: 'Playful Nature Patterns',
        image: '/fabrics/IMG_0421.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0421.jpg',
        colors: ['pink', 'red', 'brown', 'white', 'yellow', 'rainbow'],
        limited: false,
    },
    {
        name: 'Flowers & Birds',
        image: '/fabrics/IMG_0422.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0422.jpg',
        colors: ['brown', 'red', 'pink', 'blue', 'yellow', 'green', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Large Flowers',
        image: '/fabrics/IMG_0424.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0424.jpg',
        colors: ['yellow', 'brown', 'purple', 'pink', 'red', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Yellow Dandelions',
        image: '/fabrics/IMG_0423.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0423.jpg',
        colors: ['yellow', 'brown'],
        limited: false,
    },
    {
        name: 'Multicolor Dandelions',
        image: '/fabrics/IMG_0419.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0419.jpg',
        colors: ['pink', 'orange', 'yellow', 'blue', 'brown', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Brown Mandalas',
        image: '/fabrics/IMG_0416.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0416.jpg',
        colors: ['brown', 'white'],
        limited: false,
    },
    {
        name: 'Green Spirograph',
        image: '/fabrics/IMG_0445.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0445.jpg',
        colors: ['green', 'white'],
        limited: false,
    },
    {
        name: 'Orange Diamonds',
        image: '/fabrics/IMG_0444.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0444.jpg',
        colors: ['orange', 'blue', 'white'],
        limited: false,
    },
    {
        name: 'Stars & Moons',
        image: '/fabrics/IMG_0388.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0388.jpg',
        colors: ['yellow', 'grey'],
        limited: false,
    },
    {
        name: 'Pale Floral',
        image: '/fabrics/IMG_0391.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0391.jpg',
        colors: ['brown', 'white'],
        limited: false,
    },
    {
        name: 'Cool Grey Floral',
        image: '/fabrics/IMG_0413.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0413.jpg',
        colors: ['blue', 'white'],
        limited: false,
    },
    {
        name: 'Grey Paisley',
        image: '/fabrics/IMG_0403.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0403.jpg',
        colors: ['grey', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Green Paisley',
        image: '/fabrics/IMG_0404.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0404.jpg',
        colors: ['green', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Purple Paisley',
        image: '/fabrics/IMG_0405.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0405.jpg',
        colors: ['purple', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Light Purple Paisley',
        image: '/fabrics/IMG_0406.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0406.jpg',
        colors: ['purple', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Blue Floral Paisley',
        image: '/fabrics/IMG_0415.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0415.jpg',
        colors: ['blue', 'green', 'brown', 'rainbow'],
        limited: false,
    },
    {
        name: 'Light Blue Bouquets',
        image: '/fabrics/IMG_0407.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0407.jpg',
        colors: ['blue', 'pink', 'white', 'green', 'rainbow'],
        limited: false,
    },
    {
        name: 'Owls & Butterflies',
        image: '/fabrics/IMG_0412.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0412.jpg',
        colors: ['red', 'blue', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Teal Floral Diamonds',
        image: '/fabrics/IMG_0408.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0408.jpg',
        colors: ['blue', 'green', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Blue Roses',
        image: '/fabrics/IMG-0744.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0744.jpg',
        colors: ['blue'],
        limited: true,
    },
    {
        name: 'Navy Spring',
        image: '/fabrics/IMG_0409.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0409.jpg',
        colors: ['blue', 'green', 'orange', 'pink', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Navy Floral',
        image: '/fabrics/IMG_0411.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0411.jpg',
        colors: ['blue', 'yellow', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Bird Circles',
        image: '/fabrics/IMG_0410.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0410.jpg',
        colors: ['blue', 'white', 'pink', 'yellow', 'green', 'rainbow'],
        limited: false,
    },
    {
        name: 'Teal Hummingbirds',
        image: '/fabrics/IMG_0417.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0417.jpg',
        colors: ['brown', 'white', 'blue'],
        limited: false,
    },
    {
        name: 'Red & Blue Birds',
        image: '/fabrics/IMG_0441.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0441.jpg',
        colors: ['blue', 'red', 'brown', 'white', 'orange', 'rainbow'],
        limited: true,
    },
    {
        name: 'Pale Pink Flowers',
        image: '/fabrics/IMG_0420.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0420.jpg',
        colors: ['pink', 'brown', 'white', 'blue'],
        limited: false,
    },
    {
        name: 'Hawaiian Pink',
        image: '/fabrics/IMG_0402.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0402.jpg',
        colors: ['pink', 'white'],
        limited: true,
    },
    {
        name: 'Pink Mini Flowers',
        image: '/fabrics/IMG-0746.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0746.jpg',
        colors: ['pink', 'white'],
        limited: true,
    },
    {
        name: 'Ornamental Pink',
        image: '/fabrics/IMG_0429.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0429.jpg',
        colors: ['pink', 'brown', 'white'],
        limited: false,
    },
    {
        name: 'Chandelier Pink',
        image: '/fabrics/IMG_0426.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0426.jpg',
        colors: ['pink', 'brown'],
        limited: false,
    },
    {
        name: 'Elegant Pink',
        image: '/fabrics/IMG-0745.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0745.jpg',
        colors: ['pink'],
        limited: true,
    },
    {
        name: 'Wild Pink',
        image: '/fabrics/IMG-0748.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0748.jpg',
        colors: ['pink'],
        limited: true,
    },
    {
        name: 'Tickled Pink',
        image: '/fabrics/IMG-0747.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0747.jpg',
        colors: ['pink', 'orange', 'white'],
        limited: true,
    },
    {
        name: 'Pastel Feather',
        image: '/fabrics/IMG_0427.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0427.jpg',
        colors: ['black', 'brown', 'pink', 'purple', 'green', 'blue', 'rainbow'],
        limited: false,
    },
    {
        name: 'Galaxy',
        image: '/fabrics/IMG_0438.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0438.jpg',
        colors: ['blue', 'pink', 'yellow', 'black', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Lizard Camo',
        image: '/fabrics/IMG_0442.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0442.jpg',
        colors: ['red', 'blue', 'brown', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Lizards',
        image: '/fabrics/IMG-0777.jpg',
        thumbnail: '/fabrics/thumbnails/IMG-0777.jpg',
        colors: ['white', 'green', 'blue'],
        limited: true,
    },
    {
        name: 'Hawaiian Red',
        image: '/fabrics/IMG_0400.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0400.jpg',
        colors: ['red', 'white'],
        limited: true,
    },
    {
        name: 'K9 Red',
        image: '/fabrics/IMG_0401.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0401.jpg',
        colors: ['red', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Pastel Ladybugs',
        image: '/fabrics/IMG_0430.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0430.jpg',
        colors: ['pink', 'blue', 'yellow', 'brown', 'grey', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Unicorns',
        image: '/fabrics/IMG_0431.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0431.jpg',
        colors: ['blue', 'green', 'brown', 'white', 'grey', 'rainbow'],
        limited: false,
    },
    {
        name: 'Dr. Suess',
        image: '/fabrics/IMG_0433.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0433.jpg',
        colors: ['white', 'yellow', 'brown', 'green', 'red', 'blue', 'pink', 'black', 'orange', 'rainbow'],
        limited: false,
    },
    {
        name: 'Robots & Rockets',
        image: '/fabrics/IMG_0434.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0434.jpg',
        colors: ['white', 'red', 'blue', 'green', 'yellow', 'rainbow'],
        limited: false,
    },
    {
        name: 'Tinker Bell',
        image: '/fabrics/IMG_0432.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0432.jpg',
        colors: ['green', 'blue', 'pink', 'purple', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Acorns & Leaves',
        image: '/fabrics/IMG_0425.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0425.jpg',
        colors: ['brown', 'red', 'white', 'rainbow'],
        limited: false,
    },
    {
        name: 'Buttons',
        image: '/fabrics/IMG_0439.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0439.jpg',
        colors: ['blue', 'pink', 'red', 'brown', 'yellow', 'rainbow'],
        limited: false,
    },
    {
        name: 'Seashells',
        image: '/fabrics/IMG_0436.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0436.jpg',
        colors: ['blue', 'brown', 'yellow', 'orange', 'rainbow'],
        limited: true,
    },
    {
        name: 'Coffee',
        image: '/fabrics/IMG_0435.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0435.jpg',
        colors: ['brown', 'white', 'black'],
        limited: true,
    },
    {
        name: 'Architecture & Nature',
        image: '/fabrics/IMG_0437.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0437.jpg',
        colors: ['brown', 'orange', 'yellow', 'black', 'green', 'rainbow'],
        limited: false,
    },
    {
        name: 'Dark Mode Nature',
        image: '/fabrics/IMG_0440.jpg',
        thumbnail: '/fabrics/thumbnails/IMG_0440.jpg',
        colors: ['black', 'blue', 'yellow', 'pink', 'white', 'red', 'rainbow'],
        limited: false,
    },
];

export default fabricsList;